[package]
name = "kvx-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
kvx = { path = "../kvx" }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }