# kvx.toml â€” the one that started it all.
# File-to-Elasticsearch. The classic. The original. The OG.
# Like the first pancake â€” technically works, but mostly a proof of concept.
# ðŸ¦†

[runtime]
queue_capacity = 8
sink_parallelism = 8

[source_config]
max_batch_size_bytes = 131072
max_batch_size_docs = 10000

[source_config.File]
file_name = "input.json"

[sink_config]
max_request_size_bytes = 131072

[sink_config.Elasticsearch]
url = "http://localhost:9200"
index = "test-123"
