# kvx_file.toml â€” file-to-file mode.
# For when you want to migrate data without involving Elasticsearch.
# Benchmarking? Testing? Avoiding the cloud bill? We don't judge. ðŸš€
# "In a world where storage is cheap... one engineer still used files." â€” tagline, probably.
# ðŸ¦†

[runtime]
queue_capacity = 2
sink_parallelism = 1

[source_config.File]
file_name = "benchmark/rally-documents/noaa_documents.json"

[source_config.File.common_config]
max_batch_size_bytes = 268435456
max_batch_size_docs = 100000

[sink_config.File]
file_name = "output.json"
max_request_size_bytes = 268435456
