# kvx_file_to_esdb.toml ‚Äî file source, Elasticsearch sink.
# The benchmark config. The one that makes graphs go up.
# NOAA weather data into Elasticsearch because weather is a solved problem
# and yet somehow still unpredictable. Like this codebase. üå©Ô∏è
# ü¶Ü

channel_size = 10
num_sink_workers = 5

[source_config.File]
file_name = "benchmark/rally-documents/noaa_documents.json"

[source_config.File.common_config]
max_batch_size_bytes = 131072
max_batch_size_docs = 10000

[sink_config.Elasticsearch]
url = "http://localhost:9200"
index = "test-123"

[sink_config.Elasticsearch.common_config]
max_request_size_bytes = 131072
